config/routes.rb
Rails.application.routes.draw do
  
  get 'welcomes/home'
  
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root to: 'welcomes#home'
  get 'users/new'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :users do
    get 'journals/hauptbuch'
    get 'journals/konto'
    get 'journals/abschluss'
    get 'journals/createPdf'
    resources :journals 
  end
  resources :welcomes
  
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/journal.rb
#encoding: utf-8

class KontoValidator < ActiveModel::Validator
  def validate(journal)
    error_text = " existiert nicht"
    if !(IkrKontenplan.exists?(:nummer => journal.from_account_number))
      journal.errors.add(:from_account_number, :Soll_Konto_Nummer,
        message: error_text)
    end
    if !(IkrKontenplan.exists?(:nummer => journal.to_account_number))
      journal.errors.add(:to_account_number, :Haben_Konto_Nummer,
        message: error_text)
    end
    if !(IkrKontenplan.exists?(:name => journal.from_account))
      journal.errors.add(:from_account, :Soll_Konto,
        message: error_text)
    end
    if !(IkrKontenplan.exists?(:name => journal.to_account))
      journal.errors.add(:to_account, :Haben_Konto,
        message: error_text)
    end
  end
end

class Journal < ApplicationRecord
  belongs_to :user
  
  validates :from_account_number,  presence: true, length: { maximum: 50 }
  validates :from_account,  presence: true
  validates :from_amount,  presence: true, length: { maximum: 50 }
  validates :to_account_number,  presence: true, length: { maximum: 50 }
  validates :to_account,  presence: true
  validates :to_amount,  presence: true, length: { maximum: 50 }
  
  validates_with KontoValidator
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  before_action :set_journal, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user
  before_action :correct_user

  # GET /journals
  # GET /journals.json
  def index
    @user = User.find(params[:user_id])
    @journals = getJournal(params[:user_id])
    #@journals = @user.journals.all
  end

  # GET /journals/1
  # GET /journals/1.json
  def show
    #@user = User.find(params[:user_id])
    @hauptbuch = createHauptbuch(params[:user_id])
    #@tmp = "#{Rails.root}/google"
    respond_to do |format|
      format.html
      format.pdf do
        render :pdf => "show", :template => "journals/show.html.erb"
      end
    end
  end

  # GET /journals/new
  def new
    @user = User.find(params[:user_id])
    @journal = @user.journals.new
    @kontenplan = IkrKontenplan.all
  end

  # GET /journals/1/edit
  def edit
    @user = User.find(params[:user_id])
  end

  # POST /journals
  # POST /journals.json
  def create
    @user = User.find(params[:user_id])
    #@journal = Journal.new(journal_params)
    @journal = @user.journals.create(journal_params)
    
    if params[:umsatzsteuer][:soll_umsatzsteuer_id].empty? && 
      params[:umsatzsteuer][:haben_umsatzsteuer_id].empty?
      if @journal.save
        flash[:success] = "Journaleintrag erstellt"
        redirect_to new_user_journal_url(@user)
  #byebug
      else
        render 'new'
      end
    elsif params[:umsatzsteuer][:soll_umsatzsteuer_id] == "19"
      umsatzsteuerBuchen(@journal, "19", "soll")
    elsif params[:umsatzsteuer][:soll_umsatzsteuer_id] == "7"
      @journal.from_amount = (@journal.from_amount.to_f / 1.07).to_s
      @journal.to_amount = @journal.from_amount
      
      @umsatzsteuer = @journal.dup
      
      @umsatzsteuer.from_amount = (@umsatzsteuer.from_amount.to_f * 0.07).to_s
      @umsatzsteuer.to_amount = @umsatzsteuer.from_amount
      @umsatzsteuer.to_account = "Umsatzsteuer"
      @umsatzsteuer.to_account_number = "4800"
      if (@umsatzsteuer.save && @journal.save)
        flash[:success] = "2 Journaleinträge erstellt"
        redirect_to new_user_journal_url(@user)
      else  
        render 'new'
      end
    elsif params[:umsatzsteuer][:haben_umsatzsteuer_id] == "19"
      
    end

    #respond_to do |format|
      #if @journal.save
        #format.html { redirect_to @journal, notice: 'Journal was successfully created.' }
        #format.json { render :show, status: :created, location: @journal }
      #else
        #format.html { render :new }
        #format.json { render json: @journal.errors, status: :unprocessable_entity }
      #end
    #end
  end

  # PATCH/PUT /journals/1
  # PATCH/PUT /journals/1.json
  def update
    @user = User.find(params[:user_id])
    #@journal = Journal.new(journal_params)
    
    if @journal.update(journal_params)
      redirect_to user_journal_url(@user, @journal)
    end
    
    #respond_to do |format|
      #if @journal.update(journal_params)
        #format.html { redirect_to(@journal, notice: 'Journal was successfully updated.') }
        #format.json { render :show, status: :ok, location: @journal }
      #else
        #format.html { render :edit }
        #format.json { render json: @journal.errors, status: :unprocessable_entity }
      #end
    #end
  end

  # DELETE /journals/1
  # DELETE /journals/1.json
  def destroy
    @journal.destroy
    respond_to do |format|
      format.html { redirect_to user_journals_url, notice: 'Journal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def hauptbuch
    @hauptbuch = createHauptbuch(params[:user_id])
  end
  
  def konto
    createKonto(params[:user_id], params[:query])
  end
  
  def createPdf
    @hauptbuch = createHauptbuch(params[:user_id])
    @hauptbuch.each do |row|
# Exclude "Eigenkapital" from abschluss. "Eigenkapital" abschluss is done in
# createGuVBuchung
      if row[0].to_i != 3000
        @konto = createKonto(params[:user_id], row[0])
        kontoAbschliessen(@konto, row[0], row[1])
      end
    end
    
    createGuVBuchung(params[:user_id])
    
    @hauptbuch = createHauptbuch(params[:user_id])
    respond_to do |format|
      format.html
      format.pdf do
        render :pdf => "abschluss", :template => "journals/abschluss.html.erb"
               #, :page_height =>  1
      end
    end
  end
  
  def abschluss
    @hauptbuch = createHauptbuch(params[:user_id])
    @hauptbuch.each do |row|
# Exclude "Eigenkapital" from abschluss. "Eigenkapital" abschluss is done in
# createGuVBuchung
      if row[0].to_i != 3000
        @konto = createKonto(params[:user_id], row[0])
        kontoAbschliessen(@konto, row[0], row[1])
      end
    end
    
    createGuVBuchung(params[:user_id])
    
    @hauptbuch = createHauptbuch(params[:user_id])
=begin
    #@entry_created = true
    @hauptbuch = createHauptbuch(params[:user_id])
    @hauptbuch.each do |row|
# abschluss buchen ohne Eroeffnungsbilanzkonto
      if ((row[0].to_i != 8020) and (row[0].to_i != 8000) and (row[0].to_i != 3000))
        @konto = createKonto(params[:user_id], row[0])
        kontoAbschliessen(@konto, row[0], row[1])
      end
    end
    createGuVBuchung(params[:user_id])
    @konto = createKonto(params[:user_id], "8010")
    eroeffnung(@konto, params[:user_id])
=end
  end
  
  helper_method :eroeffnung, :createKonto
  
  private
  
    def umsatzsteuerBuchen(journal, prozentsatz, soll_oder_haben)
      journal.from_amount = (journal.from_amount.to_f / 1.19).to_s
=begin      
      @journal.to_amount = @journal.from_amount
      
      @umsatzsteuer = @journal.dup
      
      @umsatzsteuer.from_amount = (@umsatzsteuer.from_amount.to_f * 0.19).to_s
      @umsatzsteuer.to_amount = @umsatzsteuer.from_amount
      @umsatzsteuer.to_account = "Umsatzsteuer"
      @umsatzsteuer.to_account_number = "4800"
      if (@umsatzsteuer.save && @journal.save)
        flash[:success] = "2 Journaleinträge erstellt"
        redirect_to new_user_journal_url(@user)
      else  
        render 'new'
      end
=end
    end
    
# create buchung from GuV nach Eigenkapital
    def createGuVBuchung(user_id)
      @konto = createKonto(user_id, "8020")
      kontoAbschliessen(@konto, "8020", "GuV-Konto Gesamtkostenverfahren")
      #kontoAbschliessen(@konto, "8020", "GuV-Konto Gesamtkostenverfahren")
      @konto = createKonto(user_id, "3000")
      kontoAbschliessen(@konto, "3000", "Eigenkapital")
    end
  
    def createHauptbuch(user_id)
      @user = User.find(user_id)
      @journals = getJournal(user_id)
      #@soll_journals = @journals.distinct.pluck(:from_account_number, :from_account)
      #@haben_journals = @journals.distinct.pluck(:to_account_number, :to_account)
      @soll_journals = @journals.select('from_account_number, from_account')
      @haben_journals = @journals.select('to_account_number, to_account')
      return_array = Array.new
      @journals.each { |row|
        return_array << Array.new([row.from_account_number, row.from_account])
        return_array << Array.new([row.to_account_number, row.to_account])
      }
#      @retur_array.uniq { |s| s.first }
      return_array = return_array.uniq{|x| x[0]}
      return_array = return_array.sort_by{|x| x[0]}
#      return_array = return_array.sort_by{ |a| a[0] }
#byebug
#      @soll_journals.concat @haben_journals
#      @soll_journals = @soll_journals.uniq

      #@soll_journals = @soll_journals.order(:from_account_number)
#      @soll_journals = @soll_journals.dup.sort_by{ |a| a[0] }
      #@soll_journals = @soll_journals.sort_by{ |a| a[0] }

      return return_array
    end
  
    def createKonto(user_id, konto_number)
      @user = User.find(user_id)
      @konto_number = konto_number
      
      soll_journals = Array.new
      haben_journals = Array.new
      
      @journals = getJournal(user_id)
      @journals.each do |row|
        if row.from_account_number == @konto_number
          soll_journals << Array.new([row.to_account_number, row.to_account, row.to_amount])
        end
        if row.to_account_number == @konto_number
          haben_journals << Array.new([row.from_account_number, row.from_account, row.from_amount])
        end
      end
=begin
      @soll_journals = @journals.where(from_account_number: @konto_number).pluck(
                                        :to_account_number, :to_account,
                                        :to_amount)
      @haben_journals = @journals.where(to_account_number: @konto_number).pluck(
                                        :from_account_number, :from_account,
                                        :from_amount)
=end
      @rows_count = soll_journals.count
      if @rows_count < haben_journals.count
        @rows_count = haben_journals.count
      end
      
      @konto = Array.new
      for i in 0..(@rows_count - 1)
        if soll_journals[i].nil? then
          soll_journals[i] = Array.new(["-", "-", "-"])
        end
        if haben_journals[i].nil? then
          haben_journals[i] = Array.new(["-", "-", "-"])
        end
  
        konto_row = Array.new([soll_journals[i][0],
                                    soll_journals[i][1],
                                    soll_journals[i][2],
                                    haben_journals[i][0],
                                    haben_journals[i][1],
                                    haben_journals[i][2]])
        @konto << konto_row
      end
      return @konto
    end
    
    def kontoAbschliessen(konto, konto_number, konto_name, guv = false)
      soll_betrag = 0
      haben_betrag = 0
      konto.each do |konto_line|
        if konto_line[2] != '-'
          soll_betrag += konto_line[2].to_i
        end
        if konto_line[5] != '-'
          haben_betrag += konto_line[5].to_i
        end
      end
      
      betrag = soll_betrag - haben_betrag
      
#      targetKontoNummer = "8020"
#      targetKontoName = "GuV-Konto Gesamtkostenverfahren"

# Wenn Bestandskonto

app/helpers/journals_helper.rb
module JournalsHelper
end

app/views/journals/_form.html.erb
<%= form_for [@user, @journal] do |f| %>
  <% if journal.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(journal.errors.count, "error") %>.
    </div>
    <ul>
    <% journal.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  Soll Konto Nummer<br>
  <%= f.text_field :from_account_number, class: 'form-control' %>

  Soll Konto<br>
  <%= f.text_field :from_account, class: 'form-control' %>

  Soll Konto Betrag<br>
  <%= f.text_field :from_amount, class: 'form-control' %>
  
  Soll Konto Buchung Umsatzsteuer
  <%= f.select("post", "person_id", options_for_select([["Dollar", "$"], ["Kroner", "DKK"]]), { include_blank: true }) %>

  Haben Konto Nummer<br>
  <%= f.text_field :to_account_number, class: 'form-control' %>

  Haben Konto<br>
  <%= f.text_field :to_account, class: 'form-control' %>

  Haben Konto Betrag<br>
  <%= f.text_field :to_amount, class: 'form-control' %>


  <%= f.submit "Buchen", class: "btn btn-primary" %>
<% end %>

app/views/journals/abschluss.html.erb
<%  @hauptbuch.each do |hauptbuch_line|
      @konto = createKonto(params[:user_id], hauptbuch_line[0])
%>

<table class="table table-striped">
  <thead>
    <tr>
      <td colspan="3"><%= hauptbuch_line[0] %></td>
      <td colspan="3"><%= hauptbuch_line[1] %></td>
    </tr>
    <tr>
      <th class="border-bottom journal-width">Soll Konto Nummer</th>
      <th class="border-bottom journal-width">Soll Konto Name</th>
      <th class="border-right border-bottom journal-width">€</th>
      <th class="border-bottom journal-width">Haben Konto Nummer</th>
      <th class="border-bottom journal-width">Haben Konto Name</th>
      <th class="border-bottom journal-width">€</th>
    </tr>
  </thead>
  
  <tbody>
<%
      @konto.each do |row|
%>

      <tr>
        <td><%= row[0] %></td>
        <td><%= row[1] %></td>
        <td class="border-right"><%= row[2] %></td>
        <td><%= row[3] %></td>
        <td><%= row[4] %></td>
        <td><%= row[5] %></td>
      </tr>
    
  
<%
      end
%>
    </tbody>
  </table>
<%
    end
%>

<%    
    eroeffnung(params[:user_id])
%>

app/views/journals/createPdf.html.erb
<%  @hauptbuch.each do |hauptbuch_line|
      @konto = createKonto(params[:user_id], hauptbuch_line[0])
%>
<table class="table table-striped center">
  <thead>
    <tr>
      <td colspan="3"><%= hauptbuch_line[0] %></td>
      <td colspan="3"><%= hauptbuch_line[1] %></td>
    </tr>
    <tr class="border-bottom journal-width">
      <th class="center">Soll Konto Nummer</th>
      <th class="center">Soll Konto Name</th>
      <th class="center" id="border-right">€</th>
      <th class="center">Haben Konto Nummer</th>
      <th class="center">Haben Konto</th>
      <th class="center">€</th>
    </tr>
  </thead>
  
  <tbody>
<%
      @konto.each do |row|
%>

      <tr>
        <td><%= row[0] %></td>
        <td class="hover"><%= row[1] %></td>
        <td id="border-right"><%= row[2] %></td>
        <td><%= row[3] %></td>
        <td class="hover"><%= row[4] %></td>
        <td><%= row[5] %></td>
      </tr>
    
  
<%
      end
%>
    </tbody>
  </table>
<%
    end
%>

app/views/journals/edit.html.erb
<h1>Editing Journal</h1>

<%= render 'form', journal: @journal %>

<%= link_to 'Show', user_journal_path(@user, @journal) %> |
<%= link_to 'Back', user_journals_path %>

app/views/journals/hauptbuch.html.erb
<h1 class="center">Hauptbuch</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th class="border-bottom hauptbuch-width">Kontonummer</th>
      <th class="border-bottom hauptbuch-width">Kontoname</th>
    </tr>
  </thead>
  
  <tbody>
    <% @hauptbuch.each do |row| %>
      <tr>
        <td onmouseover="changeBackgroundColor(this, 0)" 
            onmouseout="changeBackgroundColor(this, 1)"
            onclick="changeBackgroundColor(this, 1)"
            data-link="<%= user_journals_konto_path(current_user.id, 
              query: row[0]) %>"
            class="link"
          ><%= row[0] %>
        </td>
        <td onmouseover="changeBackgroundColor(this, 0)" 
            onmouseout="changeBackgroundColor(this, 1)"
            onclick="changeBackgroundColor(this, 1)"
            data-link="<%= user_journals_konto_path(current_user.id, 
              query: row[0]) %>"
            class="link"
          ><%= row[1] %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/journals/hauptbuch_backup.html.erb
<h1 class="center">Hauptbuch</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th class="border-bottom hauptbuch-width">Soll Konto Nummer</th>
      <th class="border-right border-bottom hauptbuch-width">Soll Konto</th>
      <th class="border-bottom hauptbuch-width">Haben Konto Nummer</th>
      <th class="border-bottom hauptbuch-width">Haben Konto</th>
    </tr>
  </thead>
  
  <tbody>
    <% @hauptbuch.each do |row| %>
      <tr>
        <td <% if row[0] != "-" then %>
              onmouseover="changeBackgroundColor(this, 0)" 
              onmouseout="changeBackgroundColor(this, 1)"
              onclick="changeBackgroundColor(this, 1)"
              data-link="<%= user_journals_konto_path(current_user.id, 
                query: row[0]) %>"
              class="link"
            <% end %>
          ><%= row[0] %>
        </td>
        <td <% if row[0] != "-" then %>
              onmouseover="changeBackgroundColor(this, 0)" 
              onmouseout="changeBackgroundColor(this, 1)"
              onclick="changeBackgroundColor(this, 1)"
              data-link="<%= user_journals_konto_path(current_user.id, 
                query: row[0]) %>"
              class="link border-right"
            <% else %>
              class="border-right"
            <% end %>
          ><%= row[1] %>
        </td>
        <td <% if row[2] != "-" then %>
              onmouseover="changeBackgroundColor(this, 0)" 
              onmouseout="changeBackgroundColor(this, 1)"
              onclick="changeBackgroundColor(this, 1)"
              data-link="<%= user_journals_konto_path(current_user.id, 
                query: row[2]) %>"
              class="link"
            <% end %>
          ><%= row[2] %>
        </td>
        <td <% if row[2] != "-" then %>
              onmouseover="changeBackgroundColor(this, 0)" 
              onmouseout="changeBackgroundColor(this, 1)"
              onclick="changeBackgroundColor(this, 1)"
              data-link="<%= user_journals_konto_path(current_user.id, 
                query: row[2]) %>"
              class="link"
            <% end %>
          ><%= row[3] %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/journals/index.html.erb
<%= current_user.email %>
<br>
<%= link_to 'Neuen Journaleintrag erstellen', new_user_journal_path %>
<h1 class="center">Journaleinträge</h1>
<table class="table table-striped center">
  <thead>
    <tr class="border-bottom journal-width">
      <th class="center">Soll Konto Nummer</th>
      <th class="center">Soll Konto Name</th>
      <th class="center" id="border-right">€</th>
      <th class="center">Haben Konto Nummer</th>
      <th class="center">Haben Konto</th>
      <th class="center">€</th>
    </tr>
  </thead>
  
  <tbody>
    <% @journals.each do |journal| %>
      <tr>
        <td><%= journal.from_account_number %></td>
        <td class="hover"><%= journal.from_account %></td>
        <td id="border-right"><%= journal.from_amount %></td>
        <td><%= journal.to_account_number %></td>
        <td class="hover"><%= journal.to_account %></td>
        <td><%= journal.to_amount %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/journals/konto.html.erb
<h1>Konto</h1>
<h1><%= @konto_number %></h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th class="border-bottom konto-width">Soll Konto Nummer</th>
      <th class="border-bottom konto-width">Soll Konto</th>
      <th class="border-right border-bottom konto-width">Soll Konto Betrag</th>
      <th class="border-bottom konto-width">Haben Konto Nummer</th>
      <th class="border-bottom konto-width">Haben Konto</th>
      <th class="border-bottom konto-width">Haben Konto Betrag</th>
    </tr>
  </thead>
  
  <tbody>
    <% @konto.each do |row| %>
      <tr>
        <td>
            <%= row[0] %>
        </td>
        <td>
            <%= row[1] %>
        </td>
        <td class="border-right">
            <%= row[2] %>
        </td>
        <td>
            <%= row[3] %>
        </td>
        <td>
            <%= row[4] %>
        </td>
        <td>
            <%= row[5] %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/journals/new.html.erb
<h1>New Journal</h1>
<br>
<%= form_for [@user, @journal] do |f| %>
  <% if @journal.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize((@journal.errors.count), "error") %>.
      </div>
      <ul>
        <% @journal.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  Soll Konto Nummer<br>
  <%= f.text_field :from_account_number, class: 'form-control' %>

  Soll Konto<br>
  <%= f.text_field :from_account, class: 'form-control' %>

  Soll Konto Betrag<br>
  <%= f.text_field :from_amount, class: 'form-control', 
    onchange: "copyAmount(this)" %>

  Soll Konto Buchung Umsatzsteuer
  <%= 
    select("umsatzsteuer", "soll_umsatzsteuer_id", options_for_select([["19 %", "19"], ["7 %", "7"]]),
    { include_blank: true }, class: 'form-control')
  %>

  Haben Konto Nummer<br>
  <%= f.text_field :to_account_number, class: 'form-control' %>

  Haben Konto<br>
  <%= f.text_field :to_account, class: 'form-control' %>

  Haben Konto Betrag<br>
  <%= f.text_field :to_amount, class: 'form-control', 
    onchange: "copyAmount(this)" %>

  Haben Konto Buchung Umsatzsteuer
  <%= 
    select("umsatzsteuer", "haben_umsatzsteuer_id", options_for_select([["19 %", "19"], ["7 %", "7"]]),
    { include_blank: true }, class: 'form-control')
  %>

  <%= f.submit "Buchen", class: "btn btn-primary" %>
<% end %>

app/views/journals/show.html.erb
<%  @hauptbuch.each do |hauptbuch_line|
      @konto = createKonto(params[:user_id], hauptbuch_line[0])
%>

<table class="table table-striped">
  <thead>
    <tr>
      <th class="border-bottom journal-width">Soll Konto Nummer</th>
      <th class="border-bottom journal-width">Soll Konto Name</th>
      <th class="border-right border-bottom journal-width">€</th>
      <th class="border-bottom journal-width">Haben Konto Nummer</th>
      <th class="border-bottom journal-width">Haben Konto</th>
      <th class="border-bottom journal-width">€</th>
    </tr>
  </thead>
  
  <tbody>
<%
      @konto.each do |row|
%>

      <tr>
        <td><%= row[0] %></td>
        <td><%= row[1] %></td>
        <td class="border-right"><%= row[2] %></td>
        <td><%= row[3] %></td>
        <td><%= row[4] %></td>
        <td><%= row[5] %></td>
      </tr>
    
  
<%
      end
%>
    </tbody>
  </table>
<%
    end
%>