config/routes.rb
Rails.application.routes.draw do
  
  get 'welcomes/home'
  
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root to: 'welcomes#home'
  get 'users/new'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :users do
    get 'journals/hauptbuch'
    get 'journals/konto'
    get 'journals/abschluss'
    get 'journals/createPdf'
    resources :journals 
  end
  resources :welcomes
  
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "kibuso.de Buchhaltung", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Journal <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Journaleintrag erstellen", new_user_journal_path(current_user) %></li>
              <li><%= link_to "Journaleintraege", user_journals_path(current_user.id) %></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Hauptbuch <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Hauptbucheintraege", user_journals_hauptbuch_path(current_user.id) %></li>
              <li><%= link_to "Abschlussbuchung erstellen", user_journals_abschluss_path(current_user.id) %></li>
              <li><%= link_to "letzter Abschluss als PDF", user_journals_createPdf_path(current_user.id, :format => 'pdf') %></li>
            </ul>
          </li>
          
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Anmelden", signup_path %></li>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_header_backup.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", '#' %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div id="header">
          <%= render "layouts/header" %>
        </div>
        <div id="main">
          <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>"><%= message %></div>
          <% end %>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/backup_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div id="header">
          <%= render "layouts/header" %>
        </div>
        <div id="main">
          <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>"><%= message %></div>
          <% end %>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
<title>PDF</title>
  <%= wicked_pdf_stylesheet_link_tag "journals.scss" %>
  <%= wicked_pdf_stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= wicked_pdf_javascript_include_tag "application", "data-turbolinks-track" => true %>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
  
  <meta charset="UTF-8">
</head>
<body>

  <div class='container'>
    <%= yield %>
  </div>

</body>
</html>